// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=github.com/nurali-techie/play-go-web/goa-design-cellar/design
// --out=$(GOPATH)/src/github.com/nurali-techie/play-go-web/goa-design-cellar
// --version=v1.3.1

package app
